# Generated by Django 4.0.1 on 2023-01-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='SkyPro', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='ends_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='starts_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discounts.tour'),
            preserve_default=False,
        ),
    ]
